### ISSUE TITLE
Multiple Effects mapped to one Command

### ISSUE THREAD

**Issue by wilkinvr** [Siarl/software-design-vu#5]
## Current implementation?
When a command is entered, the `Actions` object handles it in `onCommand(Command command, Callback callback)`:

```java
    @Override
    public boolean onCommand(Command command, Callback callback) {
        if (hasCommand(command.getAction())) {
            Effect effect = getEffect(command.getAction());
            if (effect != null) {
                effect.apply(command.getGame());

                callback.onMessage("Effect applied... " + effect.toString());
            }
            return true;
        }

        return false;
    }
```

The `Effect` object mapped to the specific command string is retrieved and applied.
What exactly happens when an `Effect` is applied depends on the `Effect.Type`.

## What needs to change?
One command should be able to apply multiple effect types.

## How is this implemented?
New class `Effects` should be added. The `Effects` should contain a collection of `Effect` objects. `Effects` should also contain an `apply()` method that simply applies all the `Effect` objects at once.

Instead of mapping the command string to an `Effect` object, it should be mapped to an `Effects` object.

# TODO
*please tick off when you are done and also comment*

- [x] @sophiak2000 : update Class Diagram
- [ ] @claaudytza : update State Machine Diagram 
- [x] @Xidot : update Sequence Diagram
- [ ] @KoenVanDenBurg : update Object Diagram
- [x] @Siarl : implement changes

**Branch**: `Assignment3`

**Comment by wilkinvr** [comment]
I pushed the implementation changes
