### ISSUE TITLE
Add Characters

### ISSUE THREAD

**Issue by wilkinvr** [Siarl/software-design-vu#6]
## Current implementation?
Currently the only character in the game is the `Player':

```java
public class Player implements Interactable {

    private String name;
    private List<String> inventory;
    private PlayerStats playerStats;

   /*
    Interactable methods here
   */

   /*
    Getters & Setters here
   */
}
```

## What needs to change?
More characters should be added to the game besides the player. We need friendly characters the player can talk with and enemies the player can fight with.

## How is this implemented?
1. Abstract Class `Character` needs to be added. The `Character` will contain the implementation of the inventory (the list and also the getters and setters). The `Character` abstract should implement the `Interactable` interface.

2. The `Player` class will extend the `Character` abstract (thus removing the inventory implementation from the `Player` code).

3. A new class `Friend` (extends `Character`) needs to be added. Friends should be able to have conversations with the Player. A new class `Conversation` (extends `Interactable`) should be added and used as an attribute to `Friend`. When in a conversation, players can use a limited set of commands. The player is locked in a loop different from the main loop in `Game`.

4. A new class `Enemy` (extends `Character`) should also be added. Instead of having a conversation with the Player, Enemies can engage in combat. 
New class `Combat` should be added. When in combat, the commands the player can use are limited. The player is locked in a loop different from the main loop in `Game`. Let's keep `Combat` a simple game of rock-paper-scissors for now.

5. Characters should be maintained by the `Scene` class, as characters can only be in one scene. More info on that later.

# TODO
*please tick off when you are done and also comment*

- [ ] @Siarl : implement changes
- [x] @sophiak2000 : update Class Diagram
- [ ] @claaudytza : update State Machine Diagram 
- [x] @Xidot : update Sequence Diagram
- [ ] @KoenVanDenBurg : update Object Diagram

**Branch**: `Assignment3`

**Comment by reglayass** [comment]
ETA on completion?
